[UserSetting]
CurrentPath = ""
Parallelism = 3

[nHentai]
cf_clearance = "p1CR9OmIxGM7gYMeAZxhRlJkIP0OBuzKqNMVWVs465A-1687670089-0-250"
csrftoken = "ebeXURpz3tCoSSrk2vjm7RhDHmvqEefR80zXdmHiDLw5bpg5R1GwJbdM6QBOaqgi"
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
